# Generated by Django 5.2.14 on 2026-05-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="official_mail",
            field=models.EmailField(
                blank=True,
                help_text="Public DocPing email shown on the landing page and the legal pages (Privacy / Terms / Data Deletion), e.g. info@docping.in. Leave blank to fall back to this account's login email.",
                max_length=254,
            ),
        ),
    ]
