# Generated by Django 5.2.14 on 2026-05-29 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0007_messagetemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEventArchive",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trace_id", models.CharField(blank=True, max_length=16)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("whatsapp_number", models.CharField(blank=True, max_length=15)),
                ("user_type", models.CharField(blank=True, max_length=10)),
                ("flow", models.CharField(blank=True, max_length=40)),
                ("step", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("exc_type", models.CharField(blank=True, max_length=80)),
                ("exc_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clinic.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived log event",
                "verbose_name_plural": "Archived logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trace_id", models.CharField(blank=True, max_length=16)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("whatsapp_number", models.CharField(blank=True, max_length=15)),
                ("user_type", models.CharField(blank=True, max_length=10)),
                ("flow", models.CharField(blank=True, max_length=40)),
                ("step", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("exc_type", models.CharField(blank=True, max_length=80)),
                ("exc_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clinic.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log event",
                "verbose_name_plural": "Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="le_created_idx"),
                    models.Index(
                        fields=["trace_id", "created_at"], name="le_trace_idx"
                    ),
                    models.Index(
                        fields=["whatsapp_number", "-created_at"], name="le_wa_idx"
                    ),
                    models.Index(
                        fields=["clinic", "-created_at"], name="le_clinic_idx"
                    ),
                    models.Index(fields=["level", "-created_at"], name="le_level_idx"),
                    models.Index(fields=["event", "-created_at"], name="le_event_idx"),
                ],
            },
        ),
    ]
