# Generated by Django 5.2.14 on 2026-05-29 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_messagetemplate"),
        ("observability", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logeventarchive",
            name="clinic",
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trace_id", models.CharField(blank=True, max_length=16)),
                (
                    "request_kind",
                    models.CharField(
                        choices=[
                            ("webhook", "Webhook"),
                            ("admin", "Admin"),
                            ("task", "Celery task"),
                            ("shell", "Shell / management cmd"),
                            ("other", "Other"),
                        ],
                        default="webhook",
                        max_length=12,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warn", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("whatsapp_number", models.CharField(blank=True, max_length=15)),
                ("user_type", models.CharField(blank=True, max_length=10)),
                ("final_flow", models.CharField(blank=True, max_length=40)),
                ("final_step", models.CharField(blank=True, max_length=40)),
                ("final_event", models.CharField(blank=True, max_length=64)),
                ("inbound_text", models.CharField(blank=True, max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("event_count", models.PositiveIntegerField(default=0)),
                ("warn_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("events", models.JSONField(blank=True, default=list)),
                ("exc_type", models.CharField(blank=True, max_length=80)),
                ("exc_message", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="clinic.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Request log",
                "verbose_name_plural": "Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="LogEvent",
        ),
        migrations.DeleteModel(
            name="LogEventArchive",
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(fields=["-created_at"], name="rl_created_idx"),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(fields=["trace_id"], name="rl_trace_idx"),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["whatsapp_number", "-created_at"], name="rl_wa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(fields=["clinic", "-created_at"], name="rl_clinic_idx"),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(fields=["level", "-created_at"], name="rl_level_idx"),
        ),
        migrations.AddIndex(
            model_name="requestlog",
            index=models.Index(
                fields=["final_event", "-created_at"], name="rl_event_idx"
            ),
        ),
    ]
