# Generated by Django 5.2.14 on 2026-05-30 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinic", "0007_messagetemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("basic", "Basic — ₹999/mo"),
                            ("standard", "Standard — ₹1,999/mo"),
                            ("premium", "Premium — ₹2,999/mo"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pilot", "Free pilot"),
                            ("active", "Active"),
                            ("past_due", "Past due — grace period (7 days)"),
                            ("suspended", "Suspended — soft block"),
                            ("cancelled", "Cancelled — full stop"),
                        ],
                        default="pilot",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateField()),
                ("current_period_end", models.DateField()),
                ("pilot_ends_at", models.DateField(blank=True, null=True)),
                (
                    "monthly_amount_inr",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Agreed monthly amount in INR. 0 = pilot/free.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal billing notes — UPI ref, special terms, etc.",
                    ),
                ),
                ("doctors_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "monthly_conversation_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinic",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="clinic.clinic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_inr", models.PositiveIntegerField()),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("bank_transfer", "Bank transfer"),
                            ("cash", "Cash"),
                            ("other", "Other"),
                        ],
                        default="upi",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="UPI transaction ID, bank ref, etc.",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("paid_at", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-paid_at"],
            },
        ),
    ]
