# Generated by Django 4.0.8 on 2026-04-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('patient', 'Patient flow'), ('provider', 'Provider / Doctor flow'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Short caption shown under the video on the landing page.')),
                ('embed_url', models.URLField(blank=True, help_text='YouTube / Vimeo link. Works on Render free tier (recommended). Paste the full URL like https://youtu.be/xxxxx or https://www.youtube.com/watch?v=xxxxx')),
                ('video_file', models.FileField(blank=True, help_text='Optional direct upload. ⚠️ On Render free tier, uploaded files are lost on every redeploy — prefer a YouTube URL above for production.', null=True, upload_to='demo_videos/')),
                ('poster', models.ImageField(blank=True, help_text='Optional thumbnail shown before the viewer presses play.', null=True, upload_to='demo_posters/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first within the same role.')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'order', '-uploaded_at'],
            },
        ),
    ]
