# Generated by Django 4.0.8 on 2026-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_number', models.CharField(blank=True, help_text='Digits only, with country code. E.g. 15551773718 (Meta test bot).', max_length=20)),
                ('contact_number', models.CharField(blank=True, help_text='Digits only, with country code. Your personal WhatsApp for enquiries.', max_length=20)),
                ('contact_name', models.CharField(default='Aniket', help_text='Name shown in CTA text (e.g. "Chat with {name}").', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
