# Generated by Django 4.0.8 on 2026-04-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_seed_demo_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(db_index=True, help_text='Digits only with country code, e.g. 919876543210', max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('types', models.CharField(blank=True, help_text='Comma-separated Google Place types', max_length=200)),
                ('google_maps_url', models.URLField(blank=True)),
                ('place_id', models.CharField(blank=True, db_index=True, help_text="Google's stable Place ID", max_length=100)),
                ('score', models.IntegerField(db_index=True, default=0, help_text='Higher = better fit for our pilot')),
                ('status', models.CharField(choices=[('new', 'New — not contacted'), ('sent', 'Sent — awaiting reply'), ('replied', 'Replied — engaging'), ('demo_booked', 'Demo booked'), ('pilot', 'Pilot signed 🎉'), ('not_interested', 'Not interested'), ('invalid', 'Invalid / wrong number')], db_index=True, default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Last time the scraper saw this place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='demovideo',
            name='embed_url',
            field=models.URLField(blank=True, help_text='YouTube / Vimeo link. Works on Render free tier (recommended). Any of these works:<br> • https://youtu.be/XXXXX<br> • https://www.youtube.com/watch?v=XXXXX<br> • https://www.youtube.com/shorts/XXXXX (portrait autoplayer)'),
        ),
    ]
