# Generated by Django 4.0.8 on 2026-04-27 22:00
#
# Idempotent recovery migration. An earlier deploy on Render partially
# applied the original version: it added all 5 columns, backfilled slugs,
# then crashed when Django's AlterField on `slug` tried to re-create the
# `_like` pattern-ops index that already existed. The migration row was
# never recorded as applied, so every subsequent deploy re-runs it from the
# top and now fails on the very first AddField (because the columns are
# already there).
#
# This rewrite wraps ALL the schema work inside one RunPython that:
#   • adds each column only if it doesn't exist yet,
#   • drops any orphaned slug indexes from the failed run,
#   • backfills slug values for rows that have an empty one,
#   • adds the unique constraint + pattern-ops index cleanly.
#
# A SeparateDatabaseAndState then tells Django the 5 fields exist at the
# model-state level (so subsequent migrations and ORM use them), without
# emitting any further DDL.
#
# Vendor dispatch: PostgreSQL (Render) uses pg-specific introspection to be
# fully idempotent; SQLite (local dev) uses cross-vendor introspection.
import secrets

from django.db import migrations, models


# ─── Schema introspection helpers ─────────────────────────────────────

def _existing_columns(connection, table):
    with connection.cursor() as cur:
        return {c.name for c in connection.introspection.get_table_description(cur, table)}


def _pg_constraint_exists(cursor, table, constraint):
    cursor.execute(
        "SELECT 1 FROM information_schema.table_constraints "
        "WHERE table_name=%s AND constraint_name=%s",
        [table, constraint],
    )
    return cursor.fetchone() is not None


# ─── Slug backfill (vendor-agnostic) ──────────────────────────────────

def _backfill_slugs(apps):
    Lead = apps.get_model('marketing', 'Lead')
    used = set(Lead.objects.exclude(slug='').values_list('slug', flat=True))
    for lead in Lead.objects.filter(slug=''):
        for _ in range(8):
            candidate = secrets.token_hex(5)
            if candidate not in used:
                used.add(candidate)
                lead.slug = candidate
                lead.save(update_fields=['slug'])
                break


# ─── PostgreSQL path (Render) ─────────────────────────────────────────

def _setup_postgres(apps, schema_editor):
    db = schema_editor.connection
    table = 'marketing_lead'
    existing = _existing_columns(db, table)

    new_cols = [
        ('ai_followup_draft', "TEXT NOT NULL DEFAULT ''"),
        ('engaged_at',        'TIMESTAMP WITH TIME ZONE NULL'),
        ('last_visited_at',   'TIMESTAMP WITH TIME ZONE NULL'),
        ('visit_count',       'INTEGER NOT NULL DEFAULT 0'),
    ]
    with db.cursor() as cur:
        for col, sql_type in new_cols:
            if col not in existing:
                cur.execute(f'ALTER TABLE {table} ADD COLUMN {col} {sql_type}')

        cur.execute(
            'CREATE INDEX IF NOT EXISTS marketing_lead_engaged_at_idx '
            f'ON {table} (engaged_at)'
        )

        # Drop any orphan slug indexes left by the failed earlier run.
        cur.execute(
            "SELECT indexname FROM pg_indexes "
            "WHERE tablename=%s AND indexname LIKE %s",
            [table, '%slug%'],
        )
        for (idx_name,) in cur.fetchall():
            cur.execute(f'DROP INDEX IF EXISTS "{idx_name}"')

        if 'slug' not in existing:
            cur.execute(
                f"ALTER TABLE {table} ADD COLUMN slug VARCHAR(12) NOT NULL DEFAULT ''"
            )

    _backfill_slugs(apps)

    with db.cursor() as cur:
        if not _pg_constraint_exists(cur, table, 'marketing_lead_slug_key'):
            cur.execute(
                f'ALTER TABLE {table} ADD CONSTRAINT marketing_lead_slug_key UNIQUE (slug)'
            )
        cur.execute(
            'CREATE INDEX IF NOT EXISTS marketing_lead_slug_like_idx '
            f'ON {table} (slug varchar_pattern_ops)'
        )


# ─── SQLite path (local dev) ──────────────────────────────────────────

def _setup_sqlite(apps, schema_editor):
    db = schema_editor.connection
    table = 'marketing_lead'
    existing = _existing_columns(db, table)

    new_cols = [
        ('ai_followup_draft', "TEXT NOT NULL DEFAULT ''"),
        ('engaged_at',        'DATETIME NULL'),
        ('last_visited_at',   'DATETIME NULL'),
        ('visit_count',       'INTEGER NOT NULL DEFAULT 0'),
        ('slug',              "VARCHAR(12) NOT NULL DEFAULT ''"),
    ]
    with db.cursor() as cur:
        for col, sql_type in new_cols:
            if col not in existing:
                cur.execute(f'ALTER TABLE {table} ADD COLUMN {col} {sql_type}')

    _backfill_slugs(apps)

    with db.cursor() as cur:
        cur.execute(
            f'CREATE UNIQUE INDEX IF NOT EXISTS marketing_lead_slug_key ON {table}(slug)'
        )
        cur.execute(
            f'CREATE INDEX IF NOT EXISTS marketing_lead_engaged_at_idx ON {table}(engaged_at)'
        )


# ─── Dispatcher ───────────────────────────────────────────────────────

def setup_lead_engagement_fields(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == 'postgresql':
        _setup_postgres(apps, schema_editor)
    elif vendor == 'sqlite':
        _setup_sqlite(apps, schema_editor)
    else:
        raise NotImplementedError(
            f"Migration 0004 doesn't support DB vendor '{vendor}'. "
            "Add a handler or fall back to standard Django ops."
        )


def reverse_setup(_apps, schema_editor):
    db = schema_editor.connection
    table = 'marketing_lead'
    if db.vendor != 'postgresql':
        return
    with db.cursor() as cur:
        for col in ('slug', 'visit_count', 'last_visited_at', 'engaged_at', 'ai_followup_draft'):
            cur.execute(f'ALTER TABLE {table} DROP COLUMN IF EXISTS {col}')


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_lead_alter_demovideo_embed_url'),
    ]

    operations = [
        migrations.RunPython(setup_lead_engagement_fields, reverse_setup),
        # Tell Django the 5 fields exist at model-state level — no DDL emitted.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='lead',
                    name='ai_followup_draft',
                    field=models.TextField(blank=True, help_text='Most recent AI-drafted follow-up message (Groq); operator reviews then sends'),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='engaged_at',
                    field=models.DateTimeField(blank=True, db_index=True, help_text='First time the prospect opened their personalised landing page', null=True),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='last_visited_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='visit_count',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='lead',
                    name='slug',
                    field=models.CharField(
                        blank=True, db_index=True, max_length=12, unique=True,
                        help_text='Random hex used in the personalised landing URL /p/<slug>/',
                    ),
                ),
            ],
        ),
    ]
