# Generated by Django 4.0.8 on 2026-04-27 22:00
import secrets

from django.db import migrations, models


def backfill_slugs(apps, schema_editor):
    """Give every existing Lead a unique random slug."""
    Lead = apps.get_model('marketing', 'Lead')
    used = set(Lead.objects.exclude(slug='').values_list('slug', flat=True))
    for lead in Lead.objects.filter(slug=''):
        for _ in range(8):
            candidate = secrets.token_hex(5)
            if candidate not in used:
                used.add(candidate)
                lead.slug = candidate
                lead.save(update_fields=['slug'])
                break


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_lead_alter_demovideo_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ai_followup_draft',
            field=models.TextField(blank=True, help_text='Most recent AI-drafted follow-up message (Groq); operator reviews then sends'),
        ),
        migrations.AddField(
            model_name='lead',
            name='engaged_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='First time the prospect opened their personalised landing page', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_visited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        # Add slug as non-unique first so the column can be created on
        # tables that already have rows.
        migrations.AddField(
            model_name='lead',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Random hex used in the personalised landing URL /p/<slug>/', max_length=12),
        ),
        migrations.RunPython(backfill_slugs, reverse_noop),
        # Now that every row has a unique value, enforce uniqueness.
        migrations.AlterField(
            model_name='lead',
            name='slug',
            field=models.CharField(blank=True, db_index=True, help_text='Random hex used in the personalised landing URL /p/<slug>/', max_length=12, unique=True),
        ),
    ]
