# Generated by Django 4.0.8 on 2026-04-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_lead_ai_followup_draft_lead_engaged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_followup_at',
            field=models.DateTimeField(blank=True, help_text='Last time the operator clicked a follow-up template button — used to suppress action pill during the cooldown period.', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_followup_template',
            field=models.CharField(blank=True, help_text='Which template was used for the most recent follow-up (engaged / 3day / 7day / replied_silent).', max_length=40),
        ),
    ]
