# Generated by Django 4.0.8 on 2026-05-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_lead_last_followup_at_lead_last_followup_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arpu_inr', models.PositiveIntegerField(default=2000, help_text='Assumed monthly revenue per converted clinic (₹). Used by the pipeline-value hero.')),
                ('benchmark_new_to_sent_pct', models.PositiveSmallIntegerField(default=80, help_text='Default % of new leads we expect to contact.')),
                ('benchmark_sent_to_replied_pct', models.PositiveSmallIntegerField(default=15, help_text='Default % of sent leads expected to reply.')),
                ('benchmark_replied_to_demo_pct', models.PositiveSmallIntegerField(default=40, help_text='Default % of replied leads that book a demo.')),
                ('benchmark_demo_to_pilot_pct', models.PositiveSmallIntegerField(default=50, help_text='Default % of demos that convert to a paid pilot.')),
                ('min_sample_size', models.PositiveSmallIntegerField(default=10, help_text='Switch from benchmark to observed conversion at this stage once you have this many leads at that stage. Lower = trust your data earlier (noisier); higher = stick with benchmarks longer.')),
                ('goal_outreach_per_week', models.PositiveIntegerField(default=50)),
                ('goal_demos_per_week', models.PositiveIntegerField(default=3)),
                ('goal_pilots_per_month', models.PositiveIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard config',
                'verbose_name_plural': 'Dashboard config',
            },
        ),
    ]
