# Generated by Django 4.0.8 on 2026-04-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='display_phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='owner_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='clinic',
            name='phone_number_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='working_days',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='clinic',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
