# Generated by Django 4.0.8 on 2026-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_access_token_clinic_display_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='welcomed_at',
            field=models.DateTimeField(blank=True, help_text='Set once the welcome WhatsApp is sent', null=True),
        ),
    ]
