# Generated by Django 4.0.8 on 2026-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_doctor_welcomed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hour_before_reminded_at',
            field=models.DateTimeField(blank=True, help_text='Set when the 1-hour-before WhatsApp reminder was sent', null=True),
        ),
    ]
