# Generated by Django 4.0.8 on 2026-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_appointment_hour_before_reminded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, help_text='Per-weekday shifts. Example: {"mon":[["09:00","13:00"],["16:00","21:00"]], "sun":[]}. Leave blank to use defaults (Mon-Sat 9-1 & 4-9).'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='slot_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Slot granularity in minutes (usually 15 or 30)'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='working_days',
            field=models.CharField(blank=True, help_text="Display-only text like 'Mon-Sat'", max_length=50),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='working_hours',
            field=models.CharField(blank=True, help_text="Display-only text like 'Mon-Sat 9am-1pm, 4pm-9pm'", max_length=100),
        ),
    ]
