# Generated by Django 5.2.14 on 2026-05-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_clinic_operating_hours_clinic_slot_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="location_map_url",
            field=models.URLField(
                blank=True,
                help_text="Clinic's Google Maps short link (e.g. https://maps.app.goo.gl/AbCdEf123). Get it from Google Maps app → Share → Copy link.",
                max_length=500,
                verbose_name="Google Maps link",
            ),
        ),
    ]
