# Generated by Django 5.2.14 on 2026-05-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_clinic_location_map_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Exact Meta template name (lowercase_with_underscores). E.g. reminder_day_before",
                        max_length=80,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("UTILITY", "Utility"),
                            ("MARKETING", "Marketing"),
                            ("AUTHENTICATION", "Authentication"),
                        ],
                        default="UTILITY",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("en_US", "English (US)"),
                            ("hi", "Hindi"),
                            ("mr", "Marathi"),
                            ("bn", "Bengali"),
                            ("kha", "Khasi"),
                        ],
                        default="en",
                        help_text="Each language is a separate Meta approval.",
                        max_length=10,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Template body as approved by Meta. Use {{1}}, {{2}}, etc. for variables."
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Optional. Describe each variable. Example: [{"position":1,"label":"patient_name","example":"Priya"}]',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft — not yet submitted"),
                            ("pending", "Pending — submitted, awaiting Meta"),
                            ("approved", "Approved — ready to use ✓"),
                            ("rejected", "Rejected — fix and resubmit"),
                            ("paused", "Paused — quality issue"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "meta_template_id",
                    models.CharField(
                        blank=True,
                        help_text="Meta's internal ID (shown after approval). Optional.",
                        max_length=100,
                        verbose_name="Meta template ID",
                    ),
                ),
                (
                    "is_generic",
                    models.BooleanField(
                        default=False,
                        help_text="✓ Check to make this template usable by every clinic. Uncheck to restrict to specific clinics linked below.",
                        verbose_name="Available to all clinics",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes — why rejected, what was changed, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinics",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Clinics allowed to use this template. Ignored if 'Available to all clinics' is checked.",
                        related_name="message_templates",
                        to="clinic.clinic",
                        verbose_name="Specific clinics",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message template",
                "verbose_name_plural": "Message templates",
                "ordering": ["-is_generic", "name", "language"],
                "unique_together": {("name", "language")},
            },
        ),
    ]
