# Generated by Django 5.2.14 on 2026-06-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="enabled_languages",
            field=models.CharField(
                default="en,hi,mr",
                help_text="Languages this clinic's bot offers. Comma-separated codes: en, hi, mr. Patients see a picker only if more than one is enabled. Basic/Standard tier subscriptions are forced to English regardless.",
                max_length=50,
            ),
        ),
    ]
