# Generated by Django 5.2.14 on 2026-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_clinic_enabled_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="intake_form_url",
            field=models.URLField(
                blank=True,
                help_text="Optional. If you have a Google Form / Typeform for patient intake, paste the link here and the bot will share it with patients after they register. Leave blank to skip.",
            ),
        ),
    ]
