# Generated by Django 4.2.29 on 2026-03-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('call_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('confirmed', 'Patient Confirmed'), ('cancelled', 'Patient Cancelled via Call'), ('no_answer', 'No Answer'), ('failed', 'Call Failed')], default='initiated', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='clinic.appointment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
