# Generated by Django 4.0.8 on 2026-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=15, unique=True)),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('current_flow', models.CharField(blank=True, default='', max_length=50)),
                ('step', models.CharField(blank=True, default='', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, default='', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
