# Generated by Django 4.2.29 on 2026-03-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='clinic.clinic'),
        ),
    ]
